### ISSUE TITLE
Make weather files public

### ISSUE THREAD

**Issue by nicksisler** [NREL/OpenStudio-ERI#378]
`openstudio workflow/energy_rating_index.rb --download-weather` isn't working. It's trying to pull from http://s3.amazonaws.com/epwweatherfiles/openstudio-eri-tmy3s.zip which doesn't have public access.

**Comment by nmerket** [comment]
Nick, we had some problems about a week ago where there were suddenly hundreds of billions of requests on data in that bucket over a two day period, which caused our AWS costs to spike. To get it under control we temporarily turned off public access until we could figure out what was going on. Can you reach out to me directly at noel.merket@nrel.gov so we can talk through a way to handle this?
