### ISSUE TITLE
Auto lookup weather file

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-ERI#63]
Automatically determine TMY3 EPW from building location.

**Comment by nmerket** [comment]
We could use https://github.com/NREL/EnergyPlus/blob/develop/weather/master.geojson

**Comment by shorowit** [comment]
Apparently the OpenStudio BCL has this functionality. For example:
http://bcl.nrel.gov/api/search/location:'80401'.json?fq[]=bundle:nrel_component&fq[]=sm_vid_Component_Tags:Site&api_version=2.0
