### ISSUE TITLE
Include parallel gem in the Gemfile

### ISSUE THREAD

**Issue by rh0dium** [NREL/OpenStudio-ERI#698]
Just an FYI - Tests fail b/c parallel is not included in the gem file.

**Comment by shorowit** [comment]
@rh0dium Which tests are failing for you? All of the tests are clearly passing on GitHub Actions: https://github.com/NREL/OpenStudio-ERI/actions?query=branch%3Amaster

That said, happy to accept a PR contribution if it solves your issue.
